### ISSUE TITLE
File ignore list / ignore git folder

### ISSUE THREAD

**Issue by LlinksRechts** [kesslern/dot-templater#17]
Since a relatively frequent use case is probably to have a git repo with dot file templates, the `SRC_DIR` might also contain eg. a `.git` directory, which I don't want in my home folder. Therefore, some kind of ignore list would be helpful, eg. with a parameter:

```bash
dot-templater --ignore .git .dotconfig ~/dotfiles ~
```

An easy fix would be to just ignore `.git` altogether, this would be a breaking change though. Alternatively, a `--ignore-git` would probably suffice in most cases too.

**Comment by kesslern** [comment]
Fixed with #18
