### ISSUE TITLE
command substitution in config file

### ISSUE THREAD

**Issue by raffomania** [kesslern/dot-templater#3]
I would like to run `pass show` to automatically insert passwords in my config file. What do you think of this feature?

**Comment by kesslern** [comment]
I'd love to support this natively, but I don't see a good way to do that. Is there a Rust or C library that can retrieve passwords from the store? If so, I'd be happy implement this feature, but if not I'd rather not call an external binary from `dot-templater`.

A possible workaround would be to generate the rules file with something like a bash script that calls `pass` to add the passwords. You could also make the script delete the rules file with the passwords for an extra bit of security. I end up using a script to call `stow` to apply my dotfiles anyway, so adding this bit wouldn't be a big change in workflow.

**Comment by raffomania** [comment]
I thought of a very simple "command substitution" allowing any shell command to be executed and inserting the output in the template.
Integrating dot-templater in a custom script workflow might be a viable alternative of course. I guess it depends on the scope you have in mind for this project :)

**Comment by kesslern** [comment]
Hmm, I hadn't thought of including the ability for a generic command substitution. Good idea! That's probably worth experimenting with. If I get some time soon I'll try to fool around with this idea.

**Comment by kesslern** [comment]
This is working now. Check out the readme for details. Let me know if you have any issues!

**Comment by raffomania** [comment]
awesome, thanks!
