### ISSUE TITLE
Symlink instead of copying

### ISSUE THREAD

**Issue by ghost** [kesslern/dot-templater#5]
Why not symlink like stow?

**Comment by kesslern** [comment]
Symlinking doesn't allow the original file to change. The main purpose of this project is to produce a set of dotfiles customized for multiple computers with slightly different needs, which involves modifying the original template. Once the dotfiles are created from the template, then something like stow can be used to symlink them into place.

 I have an example of this pattern using stow in my [configs](https://github.com/kesslern/configs) repository. The `apply.sh` script uses dot-templater to create the dotfiles, then stow to symlink them into the home directory.
